# syntax=docker/dockerfile:1

FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod ./
# COPY go.sum ./
RUN go mod download

COPY . .

RUN go build -o server ./cmd/server/main.go

ARG PORT=8080

EXPOSE $PORT 

CMD [ "/app/server" ]

