name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Go 1.23.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'

    - name: Install dependencies
        run: |
          go get .
    - name: Run test
      run: make test

  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.61.0
          args: --timeout 3m --config .golangci.yaml

